project:
  type: website
  output-dir: docs
  resources:
    - Practica_01.pdf
    - Practica_02.pdf

website:
  google-analytics: "G-JMHP9PPZM4"
  #title: "osroh - website"
  page-navigation: true
  navbar:
    background: primary
    logo: IERBlanco.png
    search: true
    left:
      - text: "Sobre mi"
        file: index.qmd
      - text: "Cursos"
        menu:
          - text: "Recursos Digitales (de todo un poco)"
            href: lectures.qmd
          - text: "Eolica (Licenciatura)"
            href: lier.qmd
          - text: "Modelos (Posgrado)"
            href: posgrado.qmd
      - research.qmd
      - thesis.qmd
      - posts.qmd
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/OsvaldoRH
      - icon: youtube
        href: https://www.youtube.com/channel/UCcA6Mt8tMqm658YZKJDwgvA
  page-footer: 
    background: primary
    left: "Copyright 2023, Osvaldo Rodríguez. "
    center: "Con ayuda de [json2yaml](https://www.json2yaml.com) [DDimery](https://ddimmery.com/posts/quarto-website/) [WordCloud](https://digitalorientalist.com/2020/01/21/making-word-clouds-with-python/) [Boostwatch](https://bootswatch.com) [quarto](https://quarto.org)" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 
   
format:
  html:
    toc-title: Contenido
    toc: true
    toc-depth: 4
    theme:
        light: ier_claro.scss
        dark: ier_dark.scss
    css: styles.css
    page-layout: full

