---
title: "Repositorio digital"
format: html
execute:
  echo: false
---


# Eólica

En esta sección encontrarás algunas referencias confiables para tener un contexto de la energía eólica en México y el Mundo. También encontrarás recursos relacionados con el sector eléctrico mexicano.

[Progama de la asignatura](https://drive.google.com/file/d/0B_xgFQCM1I_VZUQzZ3NHU3JkUjA/view?resourcekey=0-s1oZCKsY2O4fmf0FdBJjLw)

-----------------------


## Recursos

<!-- ```{=html}
<div class="card-group">
    <div class="card border-primary mb-3" style="max-width: 18rem;">
        <div class="card-header">Header</div>
        <div class="card-body">
        <h5 class="card-title">Primary card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
    </div>
    <div class="card border-primary mb-3" style="max-width: 18rem;">
        <div class="card-header">Header</div>
        <div class="card-body">
        <h5 class="card-title">Primary card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
    </div>
    <div class="card border-primary mb-3" style="max-width: 18rem;">
        <div class="card-header">Header</div>
        <div class="card-body">
        <h5 class="card-title">Primary card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
    </div>
</div>
```
 -->
### IRENA
```{=html}
<iframe frameborder="100" width="100%" height="300" src="https://www.irena.org" title="IRENA"></iframe>
```

### GWEC

```{=html}
<iframe width="100%" height="300" src="https://gwec.net" title="Global Wind Energu Council"></iframe>
```

### Global Wind Energy Atlas

```{=html}
<iframe width="100%" height="300" src="https://globalwindatlas.info/es" title="Global Wind Energy Atlas"></iframe>
```

### OBTREN

```{=html}
<iframe width="100%" height="300" src="https://obtrenmx.org" title="OBTREN"></iframe>
```

[PRODESEN - SENER - 2023 -2037.](https://www.gob.mx/sener/articulos/programa-de-desarrollo-del-sistema-electrico-nacional-2023-2037)

[Mapa de ruta de la energía eólica en México](https://www.gob.mx/sener/documentos/mapas-de-ruta-tecnologica-de-energias-renovables)


-----------------------


## Python



### Sesión 1 - Elementos Python

<a class="btn btn-primary btn-sm" href="https://youtu.be/sjF3NRMaUIo" role="button">Clase grabada</a>



### Sesión 2 - Pandas

<a class="btn btn-primary btn-sm" href="https://youtu.be/Rt4EVcocMLQ" role="button">Clase grabada</a>



### Sesión 3 - Matplotlib

<a class="btn btn-primary btn-sm" href="https://youtu.be/aZO3JKYa6Cg" role="button">Clase grabada</a>



-----------------------

## Sesiones


### Sesión 1 - Contenido general del curso
<a class="btn btn-primary btn-sm" href="https://youtu.be/sjF3NRMaUIo" role="button">Clase grabada</a>



### Sesión 2 - Energía eólica en México y el Mundo
<a class="btn btn-primary btn-sm" href="https://youtu.be/Rt4EVcocMLQ" role="button">Clase grabada</a>



### Sesión 3 - Conceptos Básicos
<a class="btn btn-primary btn-sm" href="https://youtu.be/aZO3JKYa6Cg" role="button">Clase grabada</a>



### Sesión 4 - Patrones de circulación del viento
<a class="btn btn-primary btn-sm" href="https://youtu.be/2ImO2zu6NqQ" role="button">Clase grabada</a>



### Sesión 5 - Patrones de circulación del viento - Ejemplo ERA5 y energía eólica en el golfo de México

<a class="btn btn-primary btn-sm" href="https://youtu.be/8hVEa3Ml6RA" role="button">Clase grabada</a>



### Sesión 6 - Potencia en el viento
<a class="btn btn-primary btn-sm" href="https://youtu.be/nnVpddRlITE" role="button">Clase grabada</a>



### Sesión 7 - Modelos de capa límite
<a class="btn btn-primary btn-sm" href="https://youtu.be/pbRjzFxV_gQ" role="button">Clase grabada</a>




### Sesión 9 - Histogramas y FDP
<a class="btn btn-primary btn-sm" href="https://youtu.be/We23W10H4_M" role="button">Clase grabada</a>



### Sesión 10 - Ajuste de FDP en Python
<a class="btn btn-primary btn-sm" href="https://youtu.be/awknm1BcS9E" role="button">Clase grabada</a>



### Sesión 11 - Evaluación del recurso eólico
<a class="btn btn-primary btn-sm" href="https://youtu.be/Z8RjZWY5xzU" role="button">Clase grabada</a>



### Sesión 12 - Ejemplo de evaluación del recurso eólico con Python.
<a class="btn btn-primary btn-sm" href="https://youtu.be/SvrZce2KJ6M" role="button">Clase grabada</a>


### Sesión 13 - Costo de la energía
<a class="btn btn-primary btn-sm" href="https://youtu.be/XyK3yQRJ0sU" role="button">Clase grabada</a>



### Sesión 14 - Evaluación del recurso - Uso directo de los datos - Python
<a class="btn btn-primary btn-sm" href="https://youtu.be/Kt-Zdmv4m54" role="button">Clase grabada</a>



### Sesión 15 - Evaluación del recurso - Paso a Paso
<a class="btn btn-primary btn-sm" href="https://youtu.be/mkgq4UHfCa0" role="button">Clase grabada</a>



### Sesión 16 - Introducción a aerodinámica
<a class="btn btn-primary btn-sm" href="https://youtu.be/uHuxLdSzF9I" role="button">Clase grabada</a>


## Prácticas
Práctica 1
{{< pdf Practica_01.pdf width=600 height=400 >}}

Práctica 2
{{< pdf Practica_02.pdf width=600 height=400 >}}